# -*- coding: utf-8 -*-
"""Code Commenter SmokeTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0KeceN_HocGZEy049Db0-4w9TfcfK-_
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# BLOCK 1 — INSTALL ANY-LANGUAGE-CODE-COMMENTER TOOL
# Fixed tool repo. Do NOT paste your target repo here.
# ============================================================

import sys
import shutil
import subprocess
from pathlib import Path

TOOL_REPO_URL = "https://github.com/AngshulMajumdar/Any-Language-Code-Commenter.git"

WORK = Path("/content/alc_work")
TOOL_PROJECT = WORK / "Any-Language-Code-Commenter"

def run(cmd, cwd=None, check=True):
    print("\n>>>", " ".join(map(str, cmd)))
    result = subprocess.run(
        list(map(str, cmd)),
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    print(result.stdout)
    print("RETURN CODE:", result.returncode)

    if check and result.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(map(str, cmd))}")

    return result

# Clean workspace
if WORK.exists():
    shutil.rmtree(WORK)
WORK.mkdir(parents=True, exist_ok=True)

print("=== CLONING COMMENTER TOOL ===")
run(["git", "clone", TOOL_REPO_URL, TOOL_PROJECT])

print("\n=== TOOL REPO CONTENTS ===")
for p in sorted(TOOL_PROJECT.iterdir()):
    print(" -", p.name)

print("\n=== INSTALLING TOOL ===")
run([sys.executable, "-m", "pip", "install", "-U", "pip"])

install_result = run(
    [sys.executable, "-m", "pip", "install", "-e", "."],
    cwd=TOOL_PROJECT,
    check=False,
)

# If editable install fails, use source-path fallback
if install_result.returncode != 0:
    print("\nEditable install failed. Applying source-path fallback.")

    candidate_paths = []

    if (TOOL_PROJECT / "src").exists():
        candidate_paths.append(TOOL_PROJECT / "src")

    candidate_paths.append(TOOL_PROJECT)

    site_result = subprocess.run(
        [sys.executable, "-c", "import site; print(site.getsitepackages()[0])"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    site_dir = Path(site_result.stdout.strip().splitlines()[-1])
    pth_file = site_dir / "any_language_code_commenter_local.pth"

    pth_file.write_text(
        "\n".join(str(p) for p in candidate_paths) + "\n",
        encoding="utf-8",
    )

    print("Wrote fallback path file:")
    print(pth_file)
    print(pth_file.read_text())

print("\n=== IMPORT CHECK ===")
run(
    [sys.executable, "-c", "import repo_commenter; print('repo_commenter import OK')"],
    cwd=TOOL_PROJECT,
)

run(
    [sys.executable, "-c", "import repo_commenter.cli; print('repo_commenter.cli import OK')"],
    cwd=TOOL_PROJECT,
)

print("\n=== CLI HELP CHECK ===")

CLI_COMMAND = None

candidate_commands = [
    ["code-commenter", "--help"],
    ["repo-commenter", "--help"],
    ["any-language-code-commenter", "--help"],
    [sys.executable, "-m", "repo_commenter.cli", "--help"],
]

for cmd in candidate_commands:
    print("\n--- trying:", " ".join(map(str, cmd)))

    try:
        result = subprocess.run(
            list(map(str, cmd)),
            cwd=str(TOOL_PROJECT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
    except FileNotFoundError:
        print("COMMAND NOT FOUND")
        continue

    print(result.stdout)
    print("RETURN CODE:", result.returncode)

    if result.returncode == 0 and CLI_COMMAND is None:
        CLI_COMMAND = cmd[:-1]   # remove --help

if CLI_COMMAND is None:
    raise RuntimeError("The tool imports, but no CLI entry point works.")

print("\n✅ BLOCK 1 PASSED")
print("Tool installed successfully.")
print("Working CLI base command:")
print(" ".join(map(str, CLI_COMMAND)))

# Save variables for later Colab cells
# %store TOOL_PROJECT
# %store CLI_COMMAND
# %store WORK

print("\nNow stop. Next block will ask only for the repo you want to comment.")

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# BLOCK 2B — CORRECT MOCK SMOKE TEST FOR quantum-sparse-solvers
# Uses the actual CLI signature:
# code-commenter --input-repo ... --work-dir ... --output-zip ... --mock
# ============================================================

import shutil
import subprocess
from pathlib import Path

# Restore from previous cells
# %store -r TOOL_PROJECT
# %store -r CLI_COMMAND
# %store -r WORK

TARGET_REPO = WORK / "target_repo" / "quantum-sparse-solvers"
RUN_WORK_DIR = WORK / "commenter_run"
ZIP_PATH = WORK / "quantum_sparse_solvers_commented_mock.zip"

def run(cmd, cwd=None, check=True):
    print("\n>>>", " ".join(map(str, cmd)))
    result = subprocess.run(
        list(map(str, cmd)),
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    print(result.stdout)
    print("RETURN CODE:", result.returncode)

    if check and result.returncode != 0:
        raise RuntimeError("Command failed")

    return result

if not TARGET_REPO.exists():
    raise RuntimeError(f"Target repo not found: {TARGET_REPO}. Run Block 2 first.")

# Clean previous commenter run/output
if RUN_WORK_DIR.exists():
    shutil.rmtree(RUN_WORK_DIR)

if ZIP_PATH.exists():
    ZIP_PATH.unlink()

RUN_WORK_DIR.mkdir(parents=True, exist_ok=True)

print("Target repo:")
print(TARGET_REPO)

print("\nTool project:")
print(TOOL_PROJECT)

print("\nOutput zip:")
print(ZIP_PATH)

print("\n=== RUNNING MOCK COMMENTER ===")

cmd = list(CLI_COMMAND) + [
    "--input-repo", str(TARGET_REPO),
    "--work-dir", str(RUN_WORK_DIR),
    "--output-zip", str(ZIP_PATH),
    "--mock",
]

run(cmd, cwd=TOOL_PROJECT, check=True)

print("\n=== VERIFY OUTPUT STRUCTURE ===")

print("\nRun work dir contents:")
for p in sorted(RUN_WORK_DIR.rglob("*")):
    rel = p.relative_to(RUN_WORK_DIR)
    if len(rel.parts) <= 4:
        print(" -", rel)

if not ZIP_PATH.exists():
    raise RuntimeError(f"Expected zip not created: {ZIP_PATH}")

print("\nZIP created successfully:")
print(ZIP_PATH)
print("Size KB:", round(ZIP_PATH.stat().st_size / 1024, 2))

print("\n=== FIND COMMENTED FILES ===")

candidate_dirs = [
    RUN_WORK_DIR / "commented_repo",
    RUN_WORK_DIR / "commented_output",
    RUN_WORK_DIR / "output",
    RUN_WORK_DIR,
]

commented_root = None
for d in candidate_dirs:
    if d.exists() and any(d.rglob("*.py")):
        commented_root = d
        break

if commented_root is None:
    raise RuntimeError("Could not locate commented Python files inside run work dir.")

print("Commented root:")
print(commented_root)

py_files = sorted(commented_root.rglob("*.py"))
print("Python files found:", len(py_files))

for p in py_files:
    print(" -", p.relative_to(commented_root))

print("\n=== PREVIEW FIRST COMMENTED FILE ===")

preview = py_files[0]
print("Preview file:", preview.relative_to(commented_root))
text = preview.read_text(encoding="utf-8", errors="ignore")
print(text[:2500])

# Save for next block
# %store RUN_WORK_DIR
# %store ZIP_PATH
# %store commented_root

print("\n✅ BLOCK 2B PASSED")
print("Mock smoke test passed with the correct CLI arguments.")
print("Next block can run the real LLM version on this small repo.")

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# BLOCK 3 — REAL LLM COMMENTING RUN
# Runs the actual Qwen + DeepSeek models.
# Do this only after Block 2B mock mode passed.
# ============================================================

import sys
import shutil
import subprocess
from pathlib import Path

# Restore saved variables
# %store -r TOOL_PROJECT
# %store -r CLI_COMMAND
# %store -r WORK

TARGET_REPO = WORK / "target_repo" / "quantum-sparse-solvers"
REAL_WORK_DIR = WORK / "commenter_run_real"
REAL_ZIP_PATH = WORK / "quantum_sparse_solvers_commented_REAL.zip"

def run(cmd, cwd=None, check=True):
    print("\n>>>", " ".join(map(str, cmd)))
    result = subprocess.run(
        list(map(str, cmd)),
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    print(result.stdout)
    print("RETURN CODE:", result.returncode)

    if check and result.returncode != 0:
        raise RuntimeError("Command failed")

    return result

if not TARGET_REPO.exists():
    raise RuntimeError(f"Target repo not found: {TARGET_REPO}")

print("Target repo:")
print(TARGET_REPO)

print("\nTool project:")
print(TOOL_PROJECT)

print("\nReal output zip:")
print(REAL_ZIP_PATH)

print("\n=== GPU CHECK ===")
run(["nvidia-smi"], check=False)

print("\n=== INSTALL REAL LLM DEPENDENCIES ===")
run([
    sys.executable, "-m", "pip", "install", "-U",
    "transformers",
    "accelerate",
    "bitsandbytes",
    "sentencepiece",
    "safetensors"
])

# Clean previous real run
if REAL_WORK_DIR.exists():
    shutil.rmtree(REAL_WORK_DIR)

if REAL_ZIP_PATH.exists():
    REAL_ZIP_PATH.unlink()

REAL_WORK_DIR.mkdir(parents=True, exist_ok=True)

print("\n=== RUNNING REAL LLM COMMENTER ===")

cmd = list(CLI_COMMAND) + [
    "--input-repo", str(TARGET_REPO),
    "--work-dir", str(REAL_WORK_DIR),
    "--output-zip", str(REAL_ZIP_PATH),
    "--max-file-bytes", "200000",
]

run(cmd, cwd=TOOL_PROJECT, check=True)

print("\n=== VERIFY REAL OUTPUT ===")

if not REAL_ZIP_PATH.exists():
    raise RuntimeError(f"Expected real zip not created: {REAL_ZIP_PATH}")

print("Real ZIP created:")
print(REAL_ZIP_PATH)
print("Size KB:", round(REAL_ZIP_PATH.stat().st_size / 1024, 2))

print("\n=== REAL RUN WORK DIR CONTENTS ===")
for p in sorted(REAL_WORK_DIR.rglob("*")):
    rel = p.relative_to(REAL_WORK_DIR)
    if len(rel.parts) <= 4:
        print(" -", rel)

print("\n=== FIND COMMENTED PYTHON FILES ===")

candidate_dirs = [
    REAL_WORK_DIR / "commented_repo",
    REAL_WORK_DIR / "commented_output",
    REAL_WORK_DIR / "output",
    REAL_WORK_DIR,
]

real_commented_root = None
for d in candidate_dirs:
    if d.exists() and any(d.rglob("*.py")):
        real_commented_root = d
        break

if real_commented_root is None:
    raise RuntimeError("Could not locate real commented Python files.")

print("Real commented root:")
print(real_commented_root)

py_files = sorted(real_commented_root.rglob("*.py"))
print("Python files found:", len(py_files))

for p in py_files:
    print(" -", p.relative_to(real_commented_root))

print("\n=== PREVIEW FIRST REAL COMMENTED FILE ===")

preview = py_files[0]
print("Preview file:", preview.relative_to(real_commented_root))
text = preview.read_text(encoding="utf-8", errors="ignore")
print(text[:4000])

# %store REAL_WORK_DIR
# %store REAL_ZIP_PATH
# %store real_commented_root

print("\n✅ BLOCK 3 PASSED")
print("Real LLM commenting completed.")
print("Download this file from Colab:")
print(REAL_ZIP_PATH)

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# BLOCK 4 — VERIFY ZIP CONTENTS AND PREPARE DOWNLOAD FILE
# Run after Block 3 passed.
# ============================================================

import zipfile
import shutil
from pathlib import Path

# Restore variables from Block 3
# %store -r REAL_ZIP_PATH
# %store -r REAL_WORK_DIR
# %store -r real_commented_root

REAL_ZIP_PATH = Path(REAL_ZIP_PATH)
REAL_WORK_DIR = Path(REAL_WORK_DIR)
real_commented_root = Path(real_commented_root)

DOWNLOAD_ZIP = Path("/content/quantum_sparse_solvers_commented_REAL.zip")

print("Real zip path:")
print(REAL_ZIP_PATH)

if not REAL_ZIP_PATH.exists():
    raise RuntimeError(f"Real zip not found: {REAL_ZIP_PATH}")

print("\nZip size KB:", round(REAL_ZIP_PATH.stat().st_size / 1024, 2))

print("\n=== ZIP CONTENTS ===")

with zipfile.ZipFile(REAL_ZIP_PATH, "r") as zf:
    names = zf.namelist()

print("Total files in zip:", len(names))

for name in names[:80]:
    print(" -", name)

if len(names) > 80:
    print(" ...")

expected = ["qirls.py", "qols.py", "qomp.py", "qrk.py"]

print("\n=== CHECK EXPECTED PYTHON FILES ===")
for fname in expected:
    matches = [n for n in names if n.endswith(fname)]
    print(fname, "FOUND" if matches else "MISSING")
    for m in matches:
        print("   ", m)

missing = [fname for fname in expected if not any(n.endswith(fname) for n in names)]

if missing:
    raise RuntimeError(f"Missing expected files in zip: {missing}")

print("\n=== COMMENT PREVIEW FROM REAL OUTPUT ===")

py_files = sorted(real_commented_root.rglob("*.py"))

if not py_files:
    raise RuntimeError(f"No Python files found under {real_commented_root}")

for p in py_files:
    print("\n" + "=" * 80)
    print("FILE:", p.relative_to(real_commented_root))
    print("=" * 80)
    text = p.read_text(encoding="utf-8", errors="ignore")
    print(text[:2500])

print("\n=== COPY ZIP TO /content FOR EASY DOWNLOAD ===")

shutil.copy2(REAL_ZIP_PATH, DOWNLOAD_ZIP)

print("Download-ready zip:")
print(DOWNLOAD_ZIP)
print("Size KB:", round(DOWNLOAD_ZIP.stat().st_size / 1024, 2))

print("\n✅ BLOCK 4 PASSED")
print("In Colab left file browser, download:")
print(DOWNLOAD_ZIP)

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# BLOCK 5 — FINAL REPORT + OPTIONAL GOOGLE DRIVE COPY
# Run after Block 4 passed.
# ============================================================

import json
import shutil
from pathlib import Path

# %store -r REAL_ZIP_PATH
# %store -r REAL_WORK_DIR
# %store -r real_commented_root

REAL_ZIP_PATH = Path(REAL_ZIP_PATH)
REAL_WORK_DIR = Path(REAL_WORK_DIR)
real_commented_root = Path(real_commented_root)

DOWNLOAD_ZIP = Path("/content/quantum_sparse_solvers_commented_REAL.zip")

print("=== FINAL OUTPUTS ===")
print("Real zip:")
print(REAL_ZIP_PATH)
print("Exists:", REAL_ZIP_PATH.exists())

print("\nDownload zip:")
print(DOWNLOAD_ZIP)
print("Exists:", DOWNLOAD_ZIP.exists())

print("\nCommented repo root:")
print(real_commented_root)
print("Exists:", real_commented_root.exists())

if REAL_ZIP_PATH.exists():
    print("\nReal zip size KB:", round(REAL_ZIP_PATH.stat().st_size / 1024, 2))

if DOWNLOAD_ZIP.exists():
    print("Download zip size KB:", round(DOWNLOAD_ZIP.stat().st_size / 1024, 2))

print("\n=== REPORT FILES FOUND ===")

report_files = []
for pattern in ["*.json", "*.jsonl", "*.csv", "*.txt", "*.md"]:
    report_files.extend(REAL_WORK_DIR.rglob(pattern))

if not report_files:
    print("No report files found.")
else:
    for p in sorted(report_files):
        print(" -", p.relative_to(REAL_WORK_DIR))

print("\n=== QUICK SUMMARY FROM REPORTS, IF AVAILABLE ===")

for p in sorted(report_files):
    if p.suffix.lower() == ".json":
        print("\n---", p.relative_to(REAL_WORK_DIR), "---")
        try:
            data = json.loads(p.read_text(encoding="utf-8", errors="ignore"))
            if isinstance(data, dict):
                for k, v in list(data.items())[:20]:
                    print(f"{k}: {v}")
            else:
                print(str(data)[:1000])
        except Exception as e:
            print("Could not parse JSON:", e)

print("\n=== COMMENTED PYTHON FILES ===")

py_files = sorted(real_commented_root.rglob("*.py"))

if not py_files:
    print("No Python files found in commented output.")
else:
    for p in py_files:
        rel = p.relative_to(real_commented_root)
        text = p.read_text(encoding="utf-8", errors="ignore")
        comment_lines = sum(
            1 for line in text.splitlines()
            if line.strip().startswith("#")
        )
        total_lines = len(text.splitlines())
        print(f"{rel}: {comment_lines} comment lines / {total_lines} total lines")

print("\n=== OPTIONAL GOOGLE DRIVE COPY ===")

drive_root = Path("/content/drive/MyDrive")

if drive_root.exists():
    drive_dest = drive_root / "quantum_sparse_solvers_commented_REAL.zip"
    shutil.copy2(DOWNLOAD_ZIP if DOWNLOAD_ZIP.exists() else REAL_ZIP_PATH, drive_dest)
    print("Copied to Google Drive:")
    print(drive_dest)
else:
    print("Google Drive is not mounted.")
    print("To save there, run:")
    print("from google.colab import drive")
    print("drive.mount('/content/drive')")
    print("Then rerun Block 5.")

print("\n✅ BLOCK 5 COMPLETE")
print("Final downloadable file:")
print(DOWNLOAD_ZIP if DOWNLOAD_ZIP.exists() else REAL_ZIP_PATH)

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# DIAGNOSTIC — VERIFY WHETHER TWO LLMS ARE ACTUALLY USED
# ============================================================

from pathlib import Path
import json

# %store -r TOOL_PROJECT
# %store -r REAL_WORK_DIR

TOOL_PROJECT = Path(TOOL_PROJECT)
REAL_WORK_DIR = Path(REAL_WORK_DIR)

print("Tool project:", TOOL_PROJECT)
print("Real work dir:", REAL_WORK_DIR)

print("\n=== SEARCH TOOL SOURCE FOR MODEL LOADING ===")

keywords = [
    "generator_model",
    "reviewer_model",
    "Generator",
    "Reviewer",
    "AutoModel",
    "from_pretrained",
    "Qwen",
    "DeepSeek",
    "deepseek",
]

source_files = list(TOOL_PROJECT.rglob("*.py"))

for p in source_files:
    text = p.read_text(encoding="utf-8", errors="ignore")
    hits = [kw for kw in keywords if kw in text]
    if hits:
        print("\n" + "=" * 80)
        print("FILE:", p.relative_to(TOOL_PROJECT))
        print("HITS:", hits)
        print("=" * 80)
        lines = text.splitlines()
        for i, line in enumerate(lines, start=1):
            if any(kw in line for kw in keywords):
                start = max(1, i - 3)
                end = min(len(lines), i + 3)
                for j in range(start, end + 1):
                    print(f"{j:04d}: {lines[j-1]}")
                print("---")

print("\n=== SEARCH REAL RUN REPORTS FOR MODEL NAMES ===")

report_files = []
for pattern in ["*.json", "*.jsonl", "*.txt", "*.md", "*.log"]:
    report_files.extend(REAL_WORK_DIR.rglob(pattern))

if not report_files:
    print("No report/log files found in real work dir.")
else:
    for p in sorted(report_files):
        text = p.read_text(encoding="utf-8", errors="ignore")
        if any(kw.lower() in text.lower() for kw in ["generator", "reviewer", "qwen", "deepseek", "model"]):
            print("\n" + "=" * 80)
            print("REPORT:", p.relative_to(REAL_WORK_DIR))
            print("=" * 80)
            print(text[:4000])

print("\n✅ DIAGNOSTIC DONE")